
# Metadata GUI

I made a [Rshiny]() app together with two other developers, for a lab in the Princes Maxima center. This lab within the Princes Maxima center focuses on High Throughput Screening (HTS). They tend to use HTS for personalized medicine. Per example: you have a tumor biopsy, you grow these tumor cells in a 384 wells plate, you test different medication with different concentrations and than you simply select the best working one. This however creates a lot of data, such experiments are usually done with multiple plates for even more data. The solution for this is a data pipeline which is already in place at the Princes Maxima center. however one part of this pipeline couldn't be automated, the generation of metadata files. Automated generation of metadata files is usually hard to do. Metadata files contain data about what the data is about, and they are usually made by humans. Because humans know what and why they are measuring something, the measuring equipment doesn't. It just collects data while humans make sense of it. 
And this is also the case at the Princes Maxima center. They made the metadata files by hand in Excel. This process is time consuming and error prone. The app we made tackles these issues by streamlining the creation of a metadata file as much as possible. 

the app can be found here

Our approach was to make a Rshiny app that mimicked a spreadsheet application like Excel, but with certain functions that influenced an entire column. Most columns in the metadata file are all the same value so filling in that column with a single click is much faster. Also certain value's of one cell could be determined by the value's of an other cell, hereby decreasing the amount of work the user has to do. Also if the lab ever changes their experiment a value needed might not be available in a dropdown menu of one of the functions. this is why all value come from a googlesheets spreadsheet. This way the value's of each function can easily be changed. After the layout of the metadata file is final it can be downloaded as an csv .txt file.
