<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Portfolio assignment 7 | Portfolio of DSFB</title>
  <meta name="description" content="6 Portfolio assignment 7 | Portfolio of DSFB" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Portfolio assignment 7 | Portfolio of DSFB" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Portfolio assignment 7 | Portfolio of DSFB" />
  
  
  

<meta name="author" content="Lars de Groot" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="portfolio-assignment-5-b.html"/>

<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="portfolio-assignment-1-1.html"><a href="portfolio-assignment-1-1.html"><i class="fa fa-check"></i><b>1</b> Portfolio assignment 1.1</a></li>
<li class="chapter" data-level="2" data-path="portfolio-assignment-1-2-part-1.html"><a href="portfolio-assignment-1-2-part-1.html"><i class="fa fa-check"></i><b>2</b> Portfolio assignment 1.2 part 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="portfolio-assignment-1-2-part-1.html"><a href="portfolio-assignment-1-2-part-1.html#score"><i class="fa fa-check"></i><b>2.1</b> Score:</a></li>
<li class="chapter" data-level="2.2" data-path="portfolio-assignment-1-2-part-1.html"><a href="portfolio-assignment-1-2-part-1.html#explanation"><i class="fa fa-check"></i><b>2.2</b> Explanation:</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="portfolio-assignment-1-2-part-2.html"><a href="portfolio-assignment-1-2-part-2.html"><i class="fa fa-check"></i><b>3</b> Portfolio assignment 1.2 part 2</a></li>
<li class="chapter" data-level="4" data-path="portfolio-assignment-2.html"><a href="portfolio-assignment-2.html"><i class="fa fa-check"></i><b>4</b> Portfolio assignment 2</a></li>
<li class="chapter" data-level="5" data-path="portfolio-assignment-5-b.html"><a href="portfolio-assignment-5-b.html"><i class="fa fa-check"></i><b>5</b> Portfolio assignment 5.B</a></li>
<li class="chapter" data-level="6" data-path="portfolio-assignment-7.html"><a href="portfolio-assignment-7.html"><i class="fa fa-check"></i><b>6</b> Portfolio assignment 7</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Portfolio of DSFB</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="portfolio-assignment-7" class="section level1" number="6">
<h1><span class="header-section-number">6</span> Portfolio assignment 7</h1>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="portfolio-assignment-7.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">&quot;src/port_src7.R&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;A1&quot; &quot;A2&quot; &quot;A3&quot;</code></pre>
<p><strong>1. Load the flu (“./data/flu_data.csv), the dengue (.”/data/dengue_data.csv) and the gapminder ({dslabs} package) into three separate dataframes in R.</strong></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="portfolio-assignment-7.html#cb53-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;7_data/dengue_data.txt&quot;</span>), <span class="at">skip =</span> <span class="dv">11</span>) </span>
<span id="cb53-2"><a href="portfolio-assignment-7.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code></pre></div>
<pre><code>##         Date Argentina Bolivia Brazil India Indonesia Mexico Philippines Singapore Thailand Venezuela
## 1 2002-12-29        NA   0.101  0.073 0.062     0.101     NA          NA     0.059       NA        NA
## 2 2003-01-05        NA   0.143  0.098 0.047     0.039     NA          NA     0.059       NA        NA
## 3 2003-01-12        NA   0.176  0.119 0.051     0.059  0.071          NA     0.238       NA        NA
## 4 2003-01-19        NA   0.173  0.170 0.032     0.039  0.052          NA     0.175       NA        NA
## 5 2003-01-26        NA   0.146  0.138 0.040     0.112  0.048          NA     0.164       NA        NA
## 6 2003-02-02        NA   0.160  0.202 0.038     0.049  0.041          NA     0.163       NA        NA</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="portfolio-assignment-7.html#cb55-1" aria-hidden="true" tabindex="-1"></a>flu <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;7_data/flu_data.txt&quot;</span>), <span class="at">skip =</span> <span class="dv">11</span>)</span>
<span id="cb55-2"><a href="portfolio-assignment-7.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flu)</span></code></pre></div>
<pre><code>##         Date Argentina Australia Austria Belgium Bolivia Brazil Bulgaria Canada Chile France Germany Hungary Japan Mexico
## 1 2002-12-29        NA        NA      NA      NA      NA    174       NA     NA    NA     NA      NA      NA    NA     NA
## 2 2003-01-05        NA        NA      NA      NA      NA    162       NA     NA    NA     NA      NA      NA    NA     NA
## 3 2003-01-12        NA        NA      NA      NA      NA    174       NA     NA     1     NA      NA      NA    NA     NA
## 4 2003-01-19        NA        NA      NA      NA      NA    162       NA     NA     0     NA      NA      NA    NA     NA
## 5 2003-01-26        NA        NA      NA      NA      NA    131       NA     NA     0     NA      NA      NA    NA     NA
## 6 2003-02-02       136        NA      NA      NA      NA    151       NA     NA     0     NA      NA      NA    NA     NA
##   Netherlands New.Zealand Norway Paraguay Peru Poland Romania Russia South.Africa Spain Sweden Switzerland Ukraine
## 1          NA          NA     NA       NA  329     NA      NA     NA           NA    NA     NA          NA      NA
## 2          NA          NA     NA       NA  315     NA      NA     NA           NA    NA     NA          NA      NA
## 3          NA          NA     NA       NA  314     NA      NA     NA           NA    NA     NA          NA      NA
## 4          NA          NA     NA       NA  267     NA      NA     NA           NA    NA     NA          NA      NA
## 5          NA          NA     NA       NA  241     NA      NA     NA           NA    NA     NA          NA      NA
## 6          NA          NA     NA       NA  227     NA      NA     NA           NA    NA     NA          NA      NA
##   United.States Uruguay
## 1            NA      NA
## 2            NA      NA
## 3            NA      NA
## 4            NA      NA
## 5            NA      NA
## 6            NA      NA</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="portfolio-assignment-7.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gapminder)</span></code></pre></div>
<pre><code>##               country year infant_mortality life_expectancy fertility population          gdp continent          region
## 1             Albania 1960           115.40           62.87      6.19    1636054           NA    Europe Southern Europe
## 2             Algeria 1960           148.20           47.50      7.65   11124892  13828152297    Africa Northern Africa
## 3              Angola 1960           208.00           35.98      7.32    5270844           NA    Africa   Middle Africa
## 4 Antigua and Barbuda 1960               NA           62.97      4.43      54681           NA  Americas       Caribbean
## 5           Argentina 1960            59.87           65.39      3.11   20619075 108322326649  Americas   South America
## 6             Armenia 1960               NA           66.86      4.55    1867396           NA      Asia    Western Asia</code></pre>
<p><strong>2. Check if they are in the right shape. Is the data in the ‘tidy’ format? If not change the format to ‘tidy’</strong></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="portfolio-assignment-7.html#cb59-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> dengue <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(Argentina<span class="sc">:</span>Venezuela, <span class="at">names_to =</span> <span class="st">&quot;country&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;value&quot;</span>)</span>
<span id="cb59-2"><a href="portfolio-assignment-7.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   Date       country    value
##   &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;
## 1 2002-12-29 Argentina NA    
## 2 2002-12-29 Bolivia    0.101
## 3 2002-12-29 Brazil     0.073
## 4 2002-12-29 India      0.062
## 5 2002-12-29 Indonesia  0.101
## 6 2002-12-29 Mexico    NA</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="portfolio-assignment-7.html#cb61-1" aria-hidden="true" tabindex="-1"></a>flu <span class="ot">&lt;-</span> flu <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(Argentina<span class="sc">:</span>Uruguay, <span class="at">names_to =</span> <span class="st">&quot;country&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;value&quot;</span>)</span>
<span id="cb61-2"><a href="portfolio-assignment-7.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flu)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   Date       country   value
##   &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt;
## 1 2002-12-29 Argentina    NA
## 2 2002-12-29 Australia    NA
## 3 2002-12-29 Austria      NA
## 4 2002-12-29 Belgium      NA
## 5 2002-12-29 Bolivia      NA
## 6 2002-12-29 Brazil      174</code></pre>
<p><strong>3. Change the country and date variables of the three tables so that they coincide in terms of data type, class and values</strong></p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="portfolio-assignment-7.html#cb63-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> dengue <span class="sc">%&gt;%</span> <span class="fu">separate</span>(<span class="st">&quot;Date&quot;</span>, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;month&quot;</span>, <span class="st">&quot;day&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>) </span>
<span id="cb63-2"><a href="portfolio-assignment-7.html#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="portfolio-assignment-7.html#cb63-3" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> dengue[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)] </span>
<span id="cb63-4"><a href="portfolio-assignment-7.html#cb63-4" aria-hidden="true" tabindex="-1"></a>dengue<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(dengue<span class="sc">$</span>year)</span>
<span id="cb63-5"><a href="portfolio-assignment-7.html#cb63-5" aria-hidden="true" tabindex="-1"></a>dengue<span class="sc">$</span>country <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dengue<span class="sc">$</span>country)</span>
<span id="cb63-6"><a href="portfolio-assignment-7.html#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="portfolio-assignment-7.html#cb63-7" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> dengue <span class="sc">%&gt;%</span> </span>
<span id="cb63-8"><a href="portfolio-assignment-7.html#cb63-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(year, country) <span class="sc">%&gt;%</span> </span>
<span id="cb63-9"><a href="portfolio-assignment-7.html#cb63-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarise</span>(<span class="st">&quot;country&quot;</span> <span class="ot">=</span> country, <span class="st">&quot;dengue_activity&quot;</span> <span class="ot">=</span> <span class="fu">sum</span>(value, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb63-10"><a href="portfolio-assignment-7.html#cb63-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;, &#39;country&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="portfolio-assignment-7.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
## # Groups:   year, country [6]
##    year country   dengue_activity
##   &lt;int&gt; &lt;fct&gt;               &lt;dbl&gt;
## 1  2002 Argentina           0    
## 2  2002 Bolivia             0.101
## 3  2002 Brazil              0.073
## 4  2002 India               0.062
## 5  2002 Indonesia           0.101
## 6  2002 Mexico              0</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="portfolio-assignment-7.html#cb67-1" aria-hidden="true" tabindex="-1"></a>flu <span class="ot">&lt;-</span> flu <span class="sc">%&gt;%</span> <span class="fu">separate</span>(<span class="st">&quot;Date&quot;</span>, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;month&quot;</span>, <span class="st">&quot;day&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>) </span>
<span id="cb67-2"><a href="portfolio-assignment-7.html#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="portfolio-assignment-7.html#cb67-3" aria-hidden="true" tabindex="-1"></a>flu <span class="ot">&lt;-</span> flu[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)] </span>
<span id="cb67-4"><a href="portfolio-assignment-7.html#cb67-4" aria-hidden="true" tabindex="-1"></a>flu<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(flu<span class="sc">$</span>year)</span>
<span id="cb67-5"><a href="portfolio-assignment-7.html#cb67-5" aria-hidden="true" tabindex="-1"></a>flu<span class="sc">$</span>country <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(flu<span class="sc">$</span>country)</span>
<span id="cb67-6"><a href="portfolio-assignment-7.html#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="portfolio-assignment-7.html#cb67-7" aria-hidden="true" tabindex="-1"></a>flu <span class="ot">&lt;-</span> flu <span class="sc">%&gt;%</span> </span>
<span id="cb67-8"><a href="portfolio-assignment-7.html#cb67-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">group_by</span>(year, country) <span class="sc">%&gt;%</span> </span>
<span id="cb67-9"><a href="portfolio-assignment-7.html#cb67-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summarise</span>(<span class="st">&quot;country&quot;</span> <span class="ot">=</span> country, <span class="st">&quot;influenza_activity&quot;</span> <span class="ot">=</span> <span class="fu">sum</span>(value, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb67-10"><a href="portfolio-assignment-7.html#cb67-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;, &#39;country&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="portfolio-assignment-7.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flu)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
## # Groups:   year, country [6]
##    year country   influenza_activity
##   &lt;int&gt; &lt;fct&gt;                  &lt;int&gt;
## 1  2002 Argentina                  0
## 2  2002 Australia                  0
## 3  2002 Austria                    0
## 4  2002 Belgium                    0
## 5  2002 Bolivia                    0
## 6  2002 Brazil                   174</code></pre>
<p><strong>4. Store the three tables as separate (so six in total) .csv and .rds files.</strong></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="portfolio-assignment-7.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (x <span class="cf">in</span> <span class="fu">c</span>(<span class="st">&quot;flu&quot;</span>, <span class="st">&quot;dengue&quot;</span>, <span class="st">&quot;gapminder&quot;</span>)) {</span>
<span id="cb71-2"><a href="portfolio-assignment-7.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">export</span>(<span class="fu">get</span>(x), <span class="at">path =</span> <span class="fu">paste0</span>(<span class="fu">here</span>(<span class="st">&quot;7_data//&quot;</span>), x))</span>
<span id="cb71-3"><a href="portfolio-assignment-7.html#cb71-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><strong>5. In Dbeaver create a new PostgreSQL database “workflowsdb”</strong></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="portfolio-assignment-7.html#cb72-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">&quot;7_data/workflowsdb_in_Dbeaver.JPG&quot;</span>))</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-13"></span>
<img src="7_data/workflowsdb_in_Dbeaver.JPG" alt="The workflows database in Dbeaver."  />
<p class="caption">
Figure 6.1: The workflows database in Dbeaver.
</p>
</div>
<div class="figure">
<img src="C:/" alt="" />
<p class="caption">Workflows database in DBeaver</p>
</div>
<p><strong>6. Using RPostgreSQL, insert the tables into the database.</strong></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="portfolio-assignment-7.html#cb73-1" aria-hidden="true" tabindex="-1"></a>psswd <span class="ot">&lt;-</span> <span class="fu">.rs.askForPassword</span>(<span class="st">&quot;Database Password:&quot;</span>)</span>
<span id="cb73-2"><a href="portfolio-assignment-7.html#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="portfolio-assignment-7.html#cb73-3" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RPostgres<span class="sc">::</span><span class="fu">Postgres</span>(), </span>
<span id="cb73-4"><a href="portfolio-assignment-7.html#cb73-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dbname =</span> <span class="st">&quot;workflowsdb&quot;</span>, </span>
<span id="cb73-5"><a href="portfolio-assignment-7.html#cb73-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">host=</span><span class="st">&quot;localhost&quot;</span>, </span>
<span id="cb73-6"><a href="portfolio-assignment-7.html#cb73-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">port=</span><span class="st">&quot;5432&quot;</span>, </span>
<span id="cb73-7"><a href="portfolio-assignment-7.html#cb73-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">user=</span><span class="st">&quot;postgres&quot;</span>, </span>
<span id="cb73-8"><a href="portfolio-assignment-7.html#cb73-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">password=</span>psswd)</span></code></pre></div>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="portfolio-assignment-7.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">&quot;dengueDB&quot;</span>, dengue, <span class="at">overwrite =</span> T)</span>
<span id="cb74-2"><a href="portfolio-assignment-7.html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">&quot;fluDB&quot;</span>, flu, <span class="at">overwrite =</span> T)</span>
<span id="cb74-3"><a href="portfolio-assignment-7.html#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">&quot;gapminderDB&quot;</span>, gapminder, <span class="at">overwrite =</span> T)</span></code></pre></div>
<p><strong>7. Inspect the contents of the tables with SQL (in DBeaver) and save the SQL script.</strong></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb75-1"><a href="portfolio-assignment-7.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span>  <span class="kw">FROM</span> <span class="ot">&quot;dengueDB&quot;</span>;</span></code></pre></div>
<div class="knitsql-table">
<table>
<caption><span id="tab:unnamed-chunk-16">Table 6.1: </span>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="left">country</th>
<th align="right">dengue_activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Argentina</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Bolivia</td>
<td align="right">0.101</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Brazil</td>
<td align="right">0.073</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">India</td>
<td align="right">0.062</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Indonesia</td>
<td align="right">0.101</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Mexico</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Philippines</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Singapore</td>
<td align="right">0.059</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Thailand</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Venezuela</td>
<td align="right">0.000</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb76"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb76-1"><a href="portfolio-assignment-7.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span>  <span class="kw">FROM</span> <span class="ot">&quot;fluDB&quot;</span>;</span></code></pre></div>
<div class="knitsql-table">
<table>
<caption><span id="tab:unnamed-chunk-17">Table 6.2: </span>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="left">country</th>
<th align="right">influenza_activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Argentina</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Australia</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Austria</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Belgium</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Bolivia</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Brazil</td>
<td align="right">174</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Bulgaria</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">Canada</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">2002</td>
<td align="left">Chile</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">2002</td>
<td align="left">France</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb77"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb77-1"><a href="portfolio-assignment-7.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span>  <span class="kw">FROM</span> <span class="ot">&quot;gapminderDB&quot;</span>;</span></code></pre></div>
<div class="knitsql-table">
<table>
<caption><span id="tab:unnamed-chunk-18">Table 6.3: </span>Displaying records 1 - 10</caption>
<colgroup>
<col width="15%" />
<col width="3%" />
<col width="13%" />
<col width="12%" />
<col width="7%" />
<col width="8%" />
<col width="10%" />
<col width="7%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="right">year</th>
<th align="right">infant_mortality</th>
<th align="right">life_expectancy</th>
<th align="right">fertility</th>
<th align="right">population</th>
<th align="right">gdp</th>
<th align="left">continent</th>
<th align="left">region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Albania</td>
<td align="right">1960</td>
<td align="right">115.40</td>
<td align="right">62.87</td>
<td align="right">6.19</td>
<td align="right">1636054</td>
<td align="right">NA</td>
<td align="left">Europe</td>
<td align="left">Southern Europe</td>
</tr>
<tr class="even">
<td align="left">Algeria</td>
<td align="right">1960</td>
<td align="right">148.20</td>
<td align="right">47.50</td>
<td align="right">7.65</td>
<td align="right">11124892</td>
<td align="right">13828152297</td>
<td align="left">Africa</td>
<td align="left">Northern Africa</td>
</tr>
<tr class="odd">
<td align="left">Angola</td>
<td align="right">1960</td>
<td align="right">208.00</td>
<td align="right">35.98</td>
<td align="right">7.32</td>
<td align="right">5270844</td>
<td align="right">NA</td>
<td align="left">Africa</td>
<td align="left">Middle Africa</td>
</tr>
<tr class="even">
<td align="left">Antigua and Barbuda</td>
<td align="right">1960</td>
<td align="right">NA</td>
<td align="right">62.97</td>
<td align="right">4.43</td>
<td align="right">54681</td>
<td align="right">NA</td>
<td align="left">Americas</td>
<td align="left">Caribbean</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="right">1960</td>
<td align="right">59.87</td>
<td align="right">65.39</td>
<td align="right">3.11</td>
<td align="right">20619075</td>
<td align="right">108322326649</td>
<td align="left">Americas</td>
<td align="left">South America</td>
</tr>
<tr class="even">
<td align="left">Armenia</td>
<td align="right">1960</td>
<td align="right">NA</td>
<td align="right">66.86</td>
<td align="right">4.55</td>
<td align="right">1867396</td>
<td align="right">NA</td>
<td align="left">Asia</td>
<td align="left">Western Asia</td>
</tr>
<tr class="odd">
<td align="left">Aruba</td>
<td align="right">1960</td>
<td align="right">NA</td>
<td align="right">65.66</td>
<td align="right">4.82</td>
<td align="right">54208</td>
<td align="right">NA</td>
<td align="left">Americas</td>
<td align="left">Caribbean</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="right">1960</td>
<td align="right">20.30</td>
<td align="right">70.87</td>
<td align="right">3.45</td>
<td align="right">10292328</td>
<td align="right">96677859364</td>
<td align="left">Oceania</td>
<td align="left">Australia and New Zealand</td>
</tr>
<tr class="odd">
<td align="left">Austria</td>
<td align="right">1960</td>
<td align="right">37.30</td>
<td align="right">68.75</td>
<td align="right">2.70</td>
<td align="right">7065525</td>
<td align="right">52392699681</td>
<td align="left">Europe</td>
<td align="left">Western Europe</td>
</tr>
<tr class="even">
<td align="left">Azerbaijan</td>
<td align="right">1960</td>
<td align="right">NA</td>
<td align="right">61.33</td>
<td align="right">5.57</td>
<td align="right">3897889</td>
<td align="right">NA</td>
<td align="left">Asia</td>
<td align="left">Western Asia</td>
</tr>
</tbody>
</table>
</div>
<p><strong>8. Inspect the contents of the tables with dplyr (in R) and save a RMarkdown showing what you are doing.</strong></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="portfolio-assignment-7.html#cb78-1" aria-hidden="true" tabindex="-1"></a>db_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;fluDB&quot;</span>, <span class="st">&quot;dengueDB&quot;</span>, <span class="st">&quot;gapminderDB&quot;</span>)</span>
<span id="cb78-2"><a href="portfolio-assignment-7.html#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="portfolio-assignment-7.html#cb78-3" aria-hidden="true" tabindex="-1"></a>tables <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb78-4"><a href="portfolio-assignment-7.html#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> db_names){</span>
<span id="cb78-5"><a href="portfolio-assignment-7.html#cb78-5" aria-hidden="true" tabindex="-1"></a>   tables[[<span class="fu">paste</span>(i)]] <span class="ot">&lt;-</span> <span class="fu">dbReadTable</span>(con, i)</span>
<span id="cb78-6"><a href="portfolio-assignment-7.html#cb78-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="portfolio-assignment-7.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">general_inspection</span>(tables<span class="sc">$</span>fluDB, tables<span class="sc">$</span>fluDB<span class="sc">$</span>year, tables<span class="sc">$</span>fluDB<span class="sc">$</span>influenza_activity)</span></code></pre></div>
<pre><code>## [1] &quot;The data frame tables$fluDB has 3 columns: year, country, influenza_activity&quot;
## [1] &quot;And 406 rows&quot;
##       year        country          influenza_activity
##  Min.   :2002   Length:406         Min.   :     0    
##  1st Qu.:2005   Class :character   1st Qu.:  1696    
##  Median :2008   Mode  :character   Median :  6772    
##  Mean   :2008                      Mean   : 20147    
##  3rd Qu.:2012                      3rd Qu.: 24975    
##  Max.   :2015                      Max.   :155577</code></pre>
<p><img src="_main_files/figure-html/7.8%20inspection-1.png" width="672" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="portfolio-assignment-7.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">general_inspection</span>(tables<span class="sc">$</span>dengueDB, tables<span class="sc">$</span>dengueDB<span class="sc">$</span>year, tables<span class="sc">$</span>dengueDB<span class="sc">$</span>dengue_activity)</span></code></pre></div>
<pre><code>## [1] &quot;The data frame tables$dengueDB has 3 columns: year, country, dengue_activity&quot;
## [1] &quot;And 140 rows&quot;
##       year        country          dengue_activity 
##  Min.   :2002   Length:140         Min.   : 0.000  
##  1st Qu.:2005   Class :character   1st Qu.: 2.346  
##  Median :2008   Mode  :character   Median : 5.556  
##  Mean   :2008                      Mean   : 6.217  
##  3rd Qu.:2012                      3rd Qu.: 8.824  
##  Max.   :2015                      Max.   :27.847</code></pre>
<p><img src="_main_files/figure-html/7.8%20inspection-2.png" width="672" /></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="portfolio-assignment-7.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">general_inspection</span>(tables<span class="sc">$</span>gapminderDB)</span></code></pre></div>
<pre><code>## [1] &quot;The data frame tables$gapminderDB has 9 columns: country, year, infant_mortality, life_expectancy, fertility, population, gdp, continent, region&quot;
## [1] &quot;And 10545 rows&quot;
##    country               year      infant_mortality life_expectancy   fertility       population       
##  Length:10545       Min.   :1960   Min.   :  1.50   Min.   :13.20   Min.   :0.840   Min.   :3.124e+04  
##  Class :character   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50   1st Qu.:2.200   1st Qu.:1.333e+06  
##  Mode  :character   Median :1988   Median : 41.50   Median :67.54   Median :3.750   Median :5.009e+06  
##                     Mean   :1988   Mean   : 55.31   Mean   :64.81   Mean   :4.084   Mean   :2.701e+07  
##                     3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00   3rd Qu.:6.000   3rd Qu.:1.523e+07  
##                     Max.   :2016   Max.   :276.90   Max.   :83.90   Max.   :9.220   Max.   :1.376e+09  
##                                    NA&#39;s   :1453                     NA&#39;s   :187     NA&#39;s   :185        
##       gdp             continent            region         
##  Min.   :4.040e+07   Length:10545       Length:10545      
##  1st Qu.:1.846e+09   Class :character   Class :character  
##  Median :7.794e+09   Mode  :character   Mode  :character  
##  Mean   :1.480e+11                                        
##  3rd Qu.:5.540e+10                                        
##  Max.   :1.174e+13                                        
##  NA&#39;s   :2972</code></pre>
<pre><code>## Warning in general_inspection(tables$gapminderDB): missing values for x, y</code></pre>
<p><strong>9. Load the gapminder data in R and change the dataframe in such as way that you could join it to dengue and flue.</strong></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="portfolio-assignment-7.html#cb86-1" aria-hidden="true" tabindex="-1"></a>tables<span class="sc">$</span>fluDB<span class="sc">$</span>year <span class="sc">%&gt;%</span> <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>##  [1] 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="portfolio-assignment-7.html#cb88-1" aria-hidden="true" tabindex="-1"></a>tables<span class="sc">$</span>dengueDB<span class="sc">$</span>year <span class="sc">%&gt;%</span> <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>##  [1] 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015</code></pre>
<p>The data of <code>flu</code> and <code>dengue</code> are from the year 2002 untill 2015. while the data of gapminder is from:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="portfolio-assignment-7.html#cb90-1" aria-hidden="true" tabindex="-1"></a>tables<span class="sc">$</span>gapminderDB<span class="sc">$</span>year <span class="sc">%&gt;%</span> <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>##  [1] 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 2012 1976 1977 2014 1978 2016 1979
## [24] 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002
## [47] 2003 2004 2005 2006 2007 2008 2009 2010 2011 2013 2015</code></pre>
<p>1960 till 2015. we’ve also seen in 7.8 that the flu data has 406 rows while the dengue data has 140 rows.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="portfolio-assignment-7.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># db_names &lt;- c(&quot;tables$fluDB$country&quot;, &quot;tables$dengueDB$country&quot;, &quot;tables$gapminderDB$country&quot;)</span></span>
<span id="cb92-2"><a href="portfolio-assignment-7.html#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co"># for (i in db_names){</span></span>
<span id="cb92-3"><a href="portfolio-assignment-7.html#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   amount_factor(get(i)) </span></span>
<span id="cb92-4"><a href="portfolio-assignment-7.html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># } </span></span>
<span id="cb92-5"><a href="portfolio-assignment-7.html#cb92-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-6"><a href="portfolio-assignment-7.html#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">amount_factor</span>(tables<span class="sc">$</span>fluDB<span class="sc">$</span>country)</span></code></pre></div>
<pre><code>## [1] &quot;tables$fluDB$country has 29 levels:&quot;
##  [1] &quot;Argentina&quot;     &quot;Australia&quot;     &quot;Austria&quot;       &quot;Belgium&quot;       &quot;Bolivia&quot;       &quot;Brazil&quot;        &quot;Bulgaria&quot;     
##  [8] &quot;Canada&quot;        &quot;Chile&quot;         &quot;France&quot;        &quot;Germany&quot;       &quot;Hungary&quot;       &quot;Japan&quot;         &quot;Mexico&quot;       
## [15] &quot;Netherlands&quot;   &quot;New.Zealand&quot;   &quot;Norway&quot;        &quot;Paraguay&quot;      &quot;Peru&quot;          &quot;Poland&quot;        &quot;Romania&quot;      
## [22] &quot;Russia&quot;        &quot;South.Africa&quot;  &quot;Spain&quot;         &quot;Sweden&quot;        &quot;Switzerland&quot;   &quot;Ukraine&quot;       &quot;United.States&quot;
## [29] &quot;Uruguay&quot;</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="portfolio-assignment-7.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">amount_factor</span>(tables<span class="sc">$</span>dengueDB<span class="sc">$</span>country)</span></code></pre></div>
<pre><code>## [1] &quot;tables$dengueDB$country has 10 levels:&quot;
##  [1] &quot;Argentina&quot;   &quot;Bolivia&quot;     &quot;Brazil&quot;      &quot;India&quot;       &quot;Indonesia&quot;   &quot;Mexico&quot;      &quot;Philippines&quot; &quot;Singapore&quot;  
##  [9] &quot;Thailand&quot;    &quot;Venezuela&quot;</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="portfolio-assignment-7.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">amount_factor</span>(tables<span class="sc">$</span>gapminderDB<span class="sc">$</span>country)</span></code></pre></div>
<pre><code>## [1] &quot;tables$gapminderDB$country has 185 levels:&quot;
##   [1] &quot;Albania&quot;                        &quot;Algeria&quot;                        &quot;Angola&quot;                        
##   [4] &quot;Antigua and Barbuda&quot;            &quot;Argentina&quot;                      &quot;Armenia&quot;                       
##   [7] &quot;Aruba&quot;                          &quot;Australia&quot;                      &quot;Austria&quot;                       
##  [10] &quot;Azerbaijan&quot;                     &quot;Bahamas&quot;                        &quot;Bahrain&quot;                       
##  [13] &quot;Bangladesh&quot;                     &quot;Barbados&quot;                       &quot;Belarus&quot;                       
##  [16] &quot;Belgium&quot;                        &quot;Belize&quot;                         &quot;Benin&quot;                         
##  [19] &quot;Bhutan&quot;                         &quot;Bolivia&quot;                        &quot;Bosnia and Herzegovina&quot;        
##  [22] &quot;Botswana&quot;                       &quot;Brazil&quot;                         &quot;Brunei&quot;                        
##  [25] &quot;Bulgaria&quot;                       &quot;Burkina Faso&quot;                   &quot;Burundi&quot;                       
##  [28] &quot;Cambodia&quot;                       &quot;Cameroon&quot;                       &quot;Canada&quot;                        
##  [31] &quot;Cape Verde&quot;                     &quot;Central African Republic&quot;       &quot;Chad&quot;                          
##  [34] &quot;Chile&quot;                          &quot;China&quot;                          &quot;Colombia&quot;                      
##  [37] &quot;Comoros&quot;                        &quot;Congo, Dem. Rep.&quot;               &quot;Congo, Rep.&quot;                   
##  [40] &quot;Costa Rica&quot;                     &quot;Cote d&#39;Ivoire&quot;                  &quot;Croatia&quot;                       
##  [43] &quot;Cuba&quot;                           &quot;Cyprus&quot;                         &quot;Czech Republic&quot;                
##  [46] &quot;Denmark&quot;                        &quot;Djibouti&quot;                       &quot;Dominican Republic&quot;            
##  [49] &quot;Ecuador&quot;                        &quot;Egypt&quot;                          &quot;El Salvador&quot;                   
##  [52] &quot;Equatorial Guinea&quot;              &quot;Eritrea&quot;                        &quot;Estonia&quot;                       
##  [55] &quot;Ethiopia&quot;                       &quot;Fiji&quot;                           &quot;Finland&quot;                       
##  [58] &quot;France&quot;                         &quot;French Polynesia&quot;               &quot;Gabon&quot;                         
##  [61] &quot;Gambia&quot;                         &quot;Georgia&quot;                        &quot;Germany&quot;                       
##  [64] &quot;Ghana&quot;                          &quot;Greece&quot;                         &quot;Greenland&quot;                     
##  [67] &quot;Grenada&quot;                        &quot;Guatemala&quot;                      &quot;Guinea&quot;                        
##  [70] &quot;Guinea-Bissau&quot;                  &quot;Guyana&quot;                         &quot;Haiti&quot;                         
##  [73] &quot;Honduras&quot;                       &quot;Hong Kong, China&quot;               &quot;Hungary&quot;                       
##  [76] &quot;Iceland&quot;                        &quot;India&quot;                          &quot;Indonesia&quot;                     
##  [79] &quot;Iran&quot;                           &quot;Iraq&quot;                           &quot;Ireland&quot;                       
##  [82] &quot;Israel&quot;                         &quot;Italy&quot;                          &quot;Jamaica&quot;                       
##  [85] &quot;Japan&quot;                          &quot;Jordan&quot;                         &quot;Kazakhstan&quot;                    
##  [88] &quot;Kenya&quot;                          &quot;Kiribati&quot;                       &quot;Kuwait&quot;                        
##  [91] &quot;Kyrgyz Republic&quot;                &quot;Lao&quot;                            &quot;Latvia&quot;                        
##  [94] &quot;Lebanon&quot;                        &quot;Lesotho&quot;                        &quot;Liberia&quot;                       
##  [97] &quot;Libya&quot;                          &quot;Lithuania&quot;                      &quot;Luxembourg&quot;                    
## [100] &quot;Macao, China&quot;                   &quot;Macedonia, FYR&quot;                 &quot;Madagascar&quot;                    
## [103] &quot;Malawi&quot;                         &quot;Malaysia&quot;                       &quot;Maldives&quot;                      
## [106] &quot;Mali&quot;                           &quot;Malta&quot;                          &quot;Mauritania&quot;                    
## [109] &quot;Mauritius&quot;                      &quot;Mexico&quot;                         &quot;Micronesia, Fed. Sts.&quot;         
## [112] &quot;Moldova&quot;                        &quot;Mongolia&quot;                       &quot;Montenegro&quot;                    
## [115] &quot;Morocco&quot;                        &quot;Mozambique&quot;                     &quot;Namibia&quot;                       
## [118] &quot;Nepal&quot;                          &quot;Netherlands&quot;                    &quot;New Caledonia&quot;                 
## [121] &quot;New Zealand&quot;                    &quot;Nicaragua&quot;                      &quot;Niger&quot;                         
## [124] &quot;Nigeria&quot;                        &quot;Norway&quot;                         &quot;Oman&quot;                          
## [127] &quot;Pakistan&quot;                       &quot;Panama&quot;                         &quot;Papua New Guinea&quot;              
## [130] &quot;Paraguay&quot;                       &quot;Peru&quot;                           &quot;Philippines&quot;                   
## [133] &quot;Poland&quot;                         &quot;Portugal&quot;                       &quot;Puerto Rico&quot;                   
## [136] &quot;Qatar&quot;                          &quot;Romania&quot;                        &quot;Russia&quot;                        
## [139] &quot;Rwanda&quot;                         &quot;Samoa&quot;                          &quot;Saudi Arabia&quot;                  
## [142] &quot;Senegal&quot;                        &quot;Serbia&quot;                         &quot;Seychelles&quot;                    
## [145] &quot;Sierra Leone&quot;                   &quot;Singapore&quot;                      &quot;Slovak Republic&quot;               
## [148] &quot;Slovenia&quot;                       &quot;Solomon Islands&quot;                &quot;South Africa&quot;                  
## [151] &quot;South Korea&quot;                    &quot;Spain&quot;                          &quot;Sri Lanka&quot;                     
## [154] &quot;St. Lucia&quot;                      &quot;St. Vincent and the Grenadines&quot; &quot;Sudan&quot;                         
## [157] &quot;Suriname&quot;                       &quot;Swaziland&quot;                      &quot;Sweden&quot;                        
## [160] &quot;Switzerland&quot;                    &quot;Syria&quot;                          &quot;Tajikistan&quot;                    
## [163] &quot;Tanzania&quot;                       &quot;Thailand&quot;                       &quot;Timor-Leste&quot;                   
## [166] &quot;Togo&quot;                           &quot;Tonga&quot;                          &quot;Trinidad and Tobago&quot;           
## [169] &quot;Tunisia&quot;                        &quot;Turkey&quot;                         &quot;Turkmenistan&quot;                  
## [172] &quot;Uganda&quot;                         &quot;Ukraine&quot;                        &quot;United Arab Emirates&quot;          
## [175] &quot;United Kingdom&quot;                 &quot;United States&quot;                  &quot;Uruguay&quot;                       
## [178] &quot;Uzbekistan&quot;                     &quot;Vanuatu&quot;                        &quot;Venezuela&quot;                     
## [181] &quot;Vietnam&quot;                        &quot;West Bank and Gaza&quot;             &quot;Yemen&quot;                         
## [184] &quot;Zambia&quot;                         &quot;Zimbabwe&quot;</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="portfolio-assignment-7.html#cb98-1" aria-hidden="true" tabindex="-1"></a>levelF <span class="ot">&lt;-</span> tables<span class="sc">$</span>fluDB<span class="sc">$</span>country <span class="sc">%&gt;%</span> as.factor <span class="sc">%&gt;%</span> <span class="fu">levels</span>()</span>
<span id="cb98-2"><a href="portfolio-assignment-7.html#cb98-2" aria-hidden="true" tabindex="-1"></a>levelD <span class="ot">&lt;-</span> tables<span class="sc">$</span>dengueDB<span class="sc">$</span>country <span class="sc">%&gt;%</span> as.factor <span class="sc">%&gt;%</span> <span class="fu">levels</span>()</span>
<span id="cb98-3"><a href="portfolio-assignment-7.html#cb98-3" aria-hidden="true" tabindex="-1"></a>levelG <span class="ot">&lt;-</span> tables<span class="sc">$</span>gapminderDB<span class="sc">$</span>country <span class="sc">%&gt;%</span> as.factor <span class="sc">%&gt;%</span> <span class="fu">levels</span>()</span>
<span id="cb98-4"><a href="portfolio-assignment-7.html#cb98-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-5"><a href="portfolio-assignment-7.html#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">common</span>(levelD, levelG)</span></code></pre></div>
<pre><code>##  [1] &quot;Argentina&quot;   &quot;Bolivia&quot;     &quot;Brazil&quot;      &quot;India&quot;       &quot;Indonesia&quot;   &quot;Mexico&quot;      &quot;Philippines&quot; &quot;Singapore&quot;  
##  [9] &quot;Thailand&quot;    &quot;Venezuela&quot;</code></pre>
<p>All the countries in the dengue data set are all also in the gapminder dataset.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="portfolio-assignment-7.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">common</span>(levelD, levelF)</span></code></pre></div>
<pre><code>## [1] &quot;Argentina&quot; &quot;Bolivia&quot;   &quot;Brazil&quot;    &quot;Mexico&quot;</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="portfolio-assignment-7.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">common</span>(levelF, levelG) <span class="sc">%&gt;%</span> <span class="fu">length</span>()</span></code></pre></div>
<pre><code>##  [1] &quot;Argentina&quot;   &quot;Australia&quot;   &quot;Austria&quot;     &quot;Belgium&quot;     &quot;Bolivia&quot;     &quot;Brazil&quot;      &quot;Bulgaria&quot;    &quot;Canada&quot;     
##  [9] &quot;Chile&quot;       &quot;France&quot;      &quot;Germany&quot;     &quot;Hungary&quot;     &quot;Japan&quot;       &quot;Mexico&quot;      &quot;Netherlands&quot; &quot;Norway&quot;     
## [17] &quot;Paraguay&quot;    &quot;Peru&quot;        &quot;Poland&quot;      &quot;Romania&quot;     &quot;Russia&quot;      &quot;Spain&quot;       &quot;Sweden&quot;      &quot;Switzerland&quot;
## [25] &quot;Ukraine&quot;     &quot;Uruguay&quot;</code></pre>
<pre><code>## [1] 26</code></pre>
<p>but the flu data set only has in common with the dengue data set.</p>
<p>If the tables are to be joined they need to have data about only the countries and years equal to the counties and years that the tables have in common. Or the tables need to be joined in a way that <code>NA</code> is introduced where necessary.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="portfolio-assignment-7.html#cb105-1" aria-hidden="true" tabindex="-1"></a>gapminder_02_15 <span class="ot">&lt;-</span> tables<span class="sc">$</span>gapminderDB <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">between</span>(year, <span class="dv">2002</span>, <span class="dv">2015</span>))</span></code></pre></div>
<p><strong>10. Save this clean gapminder data in the “workflowsdb” database</strong></p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="portfolio-assignment-7.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">&quot;gapminder_02_15DB&quot;</span>, gapminder_02_15, <span class="at">overwrite =</span> T)</span></code></pre></div>
<p><strong>11. Perform some joins (your choice) with SQL (can be done in DBeaver or with dplyr).</strong></p>
<div class="sourceCode" id="cb107"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb107-1"><a href="portfolio-assignment-7.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="op">*</span>, <span class="ot">&quot;fluDB&quot;</span>.influenza_activity, <span class="ot">&quot;dengueDB&quot;</span>.dengue_activity </span>
<span id="cb107-2"><a href="portfolio-assignment-7.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> <span class="ot">&quot;gapminder_02_15DB&quot;</span></span>
<span id="cb107-3"><a href="portfolio-assignment-7.html#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> <span class="ot">&quot;fluDB&quot;</span> <span class="kw">ON</span> <span class="kw">public</span>.<span class="ot">&quot;fluDB&quot;</span>.<span class="dt">year</span> <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="dt">year</span> </span>
<span id="cb107-4"><a href="portfolio-assignment-7.html#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> <span class="kw">public</span>.<span class="ot">&quot;fluDB&quot;</span>.country <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.country</span>
<span id="cb107-5"><a href="portfolio-assignment-7.html#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> <span class="ot">&quot;dengueDB&quot;</span> <span class="kw">ON</span> <span class="kw">public</span>.<span class="ot">&quot;dengueDB&quot;</span>.<span class="dt">year</span> <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="dt">year</span></span>
<span id="cb107-6"><a href="portfolio-assignment-7.html#cb107-6" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> <span class="kw">public</span>.<span class="ot">&quot;dengueDB&quot;</span>.country <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.country</span></code></pre></div>
<div class="knitsql-table">
<table style="width:100%;">
<caption><span id="tab:unnamed-chunk-27">Table 6.4: </span>Displaying records 1 - 10</caption>
<colgroup>
<col width="6%" />
<col width="3%" />
<col width="11%" />
<col width="10%" />
<col width="6%" />
<col width="7%" />
<col width="8%" />
<col width="6%" />
<col width="16%" />
<col width="12%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="right">year</th>
<th align="right">infant_mortality</th>
<th align="right">life_expectancy</th>
<th align="right">fertility</th>
<th align="right">population</th>
<th align="right">gdp</th>
<th align="left">continent</th>
<th align="left">region</th>
<th align="right">influenza_activity</th>
<th align="right">dengue_activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Argentina</td>
<td align="right">2002</td>
<td align="right">17.1</td>
<td align="right">74.3</td>
<td align="right">2.38</td>
<td align="right">37889443</td>
<td align="right">2.420762e+11</td>
<td align="left">Americas</td>
<td align="left">South America</td>
<td align="right">0</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">Australia</td>
<td align="right">2002</td>
<td align="right">5.0</td>
<td align="right">80.3</td>
<td align="right">1.76</td>
<td align="right">19514385</td>
<td align="right">4.421354e+11</td>
<td align="left">Oceania</td>
<td align="left">Australia and New Zealand</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left">Austria</td>
<td align="right">2002</td>
<td align="right">4.4</td>
<td align="right">78.8</td>
<td align="right">1.39</td>
<td align="right">8114698</td>
<td align="right">1.969986e+11</td>
<td align="left">Europe</td>
<td align="left">Western Europe</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Belgium</td>
<td align="right">2002</td>
<td align="right">4.4</td>
<td align="right">78.2</td>
<td align="right">1.68</td>
<td align="right">10364613</td>
<td align="right">2.377417e+11</td>
<td align="left">Europe</td>
<td align="left">Western Europe</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left">Bolivia</td>
<td align="right">2002</td>
<td align="right">53.7</td>
<td align="right">68.7</td>
<td align="right">3.98</td>
<td align="right">8653343</td>
<td align="right">8.751510e+09</td>
<td align="left">Americas</td>
<td align="left">South America</td>
<td align="right">0</td>
<td align="right">0.101</td>
</tr>
<tr class="even">
<td align="left">Brazil</td>
<td align="right">2002</td>
<td align="right">24.3</td>
<td align="right">71.4</td>
<td align="right">2.26</td>
<td align="right">181045592</td>
<td align="right">6.705127e+11</td>
<td align="left">Americas</td>
<td align="left">South America</td>
<td align="right">174</td>
<td align="right">0.073</td>
</tr>
<tr class="odd">
<td align="left">Bulgaria</td>
<td align="right">2002</td>
<td align="right">16.3</td>
<td align="right">72.1</td>
<td align="right">1.22</td>
<td align="right">7869124</td>
<td align="right">1.406418e+10</td>
<td align="left">Europe</td>
<td align="left">Eastern Europe</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Canada</td>
<td align="right">2002</td>
<td align="right">5.3</td>
<td align="right">79.6</td>
<td align="right">1.51</td>
<td align="right">31288572</td>
<td align="right">7.594286e+11</td>
<td align="left">Americas</td>
<td align="left">Northern America</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left">Chile</td>
<td align="right">2002</td>
<td align="right">8.3</td>
<td align="right">77.7</td>
<td align="right">2.01</td>
<td align="right">15544554</td>
<td align="right">7.944855e+10</td>
<td align="left">Americas</td>
<td align="left">South America</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">France</td>
<td align="right">2002</td>
<td align="right">4.2</td>
<td align="right">79.4</td>
<td align="right">1.87</td>
<td align="right">60075783</td>
<td align="right">1.363229e+12</td>
<td align="left">Europe</td>
<td align="left">Western Europe</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<p><strong>12. Generate a joined table, and export this from the database to R.</strong></p>
<div class="sourceCode" id="cb108"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb108-1"><a href="portfolio-assignment-7.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> joined_gapfluden </span>
<span id="cb108-2"><a href="portfolio-assignment-7.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="kw">AS</span> <span class="kw">SELECT</span> <span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="op">*</span>, <span class="ot">&quot;fluDB&quot;</span>.influenza_activity, <span class="ot">&quot;dengueDB&quot;</span>.dengue_activity </span>
<span id="cb108-3"><a href="portfolio-assignment-7.html#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> <span class="ot">&quot;gapminder_02_15DB&quot;</span></span>
<span id="cb108-4"><a href="portfolio-assignment-7.html#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> <span class="ot">&quot;fluDB&quot;</span> <span class="kw">ON</span> <span class="kw">public</span>.<span class="ot">&quot;fluDB&quot;</span>.<span class="dt">year</span> <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="dt">year</span> </span>
<span id="cb108-5"><a href="portfolio-assignment-7.html#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> <span class="kw">public</span>.<span class="ot">&quot;fluDB&quot;</span>.country <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.country</span>
<span id="cb108-6"><a href="portfolio-assignment-7.html#cb108-6" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> <span class="ot">&quot;dengueDB&quot;</span> <span class="kw">ON</span> <span class="kw">public</span>.<span class="ot">&quot;dengueDB&quot;</span>.<span class="dt">year</span> <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.<span class="dt">year</span></span>
<span id="cb108-7"><a href="portfolio-assignment-7.html#cb108-7" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> <span class="kw">public</span>.<span class="ot">&quot;dengueDB&quot;</span>.country <span class="op">=</span> <span class="kw">public</span>.<span class="ot">&quot;gapminder_02_15DB&quot;</span>.country</span></code></pre></div>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="portfolio-assignment-7.html#cb109-1" aria-hidden="true" tabindex="-1"></a>joined_gapfluden <span class="ot">&lt;-</span> <span class="fu">dbReadTable</span>(<span class="at">conn =</span> con, <span class="st">&quot;joined_gapfluden&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="portfolio-assignment-7.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbDisconnect</span>(con)</span></code></pre></div>
<p><strong>13. Show some descriptive statistics with this table, and at least 3 visualisations using ggplot2.</strong></p>
<p>First of all i there is no description what <code>influenza activity</code> actually is. I assume because its only positive integers that it means individuals infected. So i want to see if population has a correlation with <code>influenza activity</code>.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="portfolio-assignment-7.html#cb111-1" aria-hidden="true" tabindex="-1"></a>joined_gapfluden <span class="sc">%&gt;%</span> <span class="fu">filter</span>(influenza_activity <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb111-2"><a href="portfolio-assignment-7.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> influenza_activity, <span class="at">y=</span>population))<span class="sc">+</span></span>
<span id="cb111-3"><a href="portfolio-assignment-7.html#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb111-4"><a href="portfolio-assignment-7.html#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>year)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="portfolio-assignment-5-b.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
